FROM openjdk:9-jdk-slim

ENV SPRING_OUTPUT_ANSI_ENABLED=ALWAYS \
    JHIPSTER_SLEEP=0 \
    JAVA_OPTS=""

# Set the working directory
WORKDIR /qualopt

# Copy the current directory contents into the container
ADD . /qualopt

# Make port 8080 available to the world outside this container
EXPOSE 8080
EXPOSE 9000
EXPOSE 3001

RUN apt-get update

RUN apt-get --yes install curl bash gnupg build-essential

RUN curl -sL https://deb.nodesource.com/setup_9.x | /bin/bash

RUN apt-get --yes install nodejs

RUN npm install -g yarn node-gyp

# RUN ./mvnw -Pdev package

# Run app when the container launches
CMD ["/bin/bash"]
